#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.A9F{1,0,7.2,1
#
app.xa9fg: package/cfg/app.xa9fg.mak

clean::
	-$(RM) package/cfg/app.xa9fg.mak
