#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = xconfig_app
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/utils.js:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/utils.js
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xdc.tci:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xdc.tci
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/template.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/template.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/om2.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/om2.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xmlgen.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xmlgen.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/xmlgen2.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/Warnings.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/Warnings.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/IPackage.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/IPackage.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/package.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/package.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/global/Clock.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/global/Trace.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/bld.js:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/bld.js
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/BuildEnvironment.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/PackageContents.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/_gen.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Library.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Library.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Executable.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Repository.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Configuration.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Script.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Script.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Manifest.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/Utils.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget2.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITarget3.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/ITargetFilter.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/package.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/bios_6_76_03_01/packages/gnu/targets/ITarget.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/ITarget.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/_utils.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/_utils.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/Linux86.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/Linux86.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/Mingw.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/Mingw.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/package.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/package.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/ITarget.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/ITarget.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/GCArmv6.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/GCArmv7A.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/IM.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/IM.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/M3.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/M3.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A8F.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A8F.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A9F.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A9F.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A15F.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A15F.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A53F.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/A53F.xs
C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/package.xs:
package.mak: C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/package.xs
package.mak: package.bld
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/io/File.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/io/File.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/io/package.xs:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/services/io/package.xs
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/ccs1020/xdctools_3_62_00_08_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.A9F.rootDir ?= C:/ti/ccs1020/ccs/tools/compiler/gcc-arm-none-eabi-7-2017-q4-major-win32
gnu.targets.arm.packageBase ?= C:/ti/bios_6_76_03_01/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oa9fg
.PHONY: all,a9fg .dlls,a9fg .executables,a9fg test,a9fg
all,a9fg: .executables,a9fg
.executables,a9fg: .libraries,a9fg
.executables,a9fg: .dlls,a9fg
.dlls,a9fg: .libraries,a9fg
.libraries,a9fg: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,a9fg
	@$(ECHO) xdc .executables,a9fg
	@$(ECHO) xdc .libraries,a9fg
	@$(ECHO) xdc .dlls,a9fg


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_xconfig_app.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package xconfig_app" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,a9fg .dlls: app.pa9fg

-include package/cfg/app_pa9fg.mak
-include package/cfg/app_pa9fg.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_pa9fg.dep
endif
app.pa9fg: package/cfg/app_pa9fg.xdl
	@


ifeq (,$(wildcard .libraries,a9fg))
app.pa9fg package/cfg/app_pa9fg.c: .libraries,a9fg
endif

package/cfg/app_pa9fg.c package/cfg/app_pa9fg.h package/cfg/app_pa9fg.xdl: override _PROG_NAME := app.xa9fg
package/cfg/app_pa9fg.c: package/cfg/app_pa9fg.cfg
package/cfg/app_pa9fg.xdc.inc: package/cfg/app_pa9fg.xdl
package/cfg/app_pa9fg.xdl package/cfg/app_pa9fg.c: .interfaces

clean:: clean,a9fg
	-$(RM) package/cfg/app_pa9fg.cfg
	-$(RM) package/cfg/app_pa9fg.dep
	-$(RM) package/cfg/app_pa9fg.c
	-$(RM) package/cfg/app_pa9fg.xdc.inc

clean,a9fg::
	-$(RM) app.pa9fg
.executables,a9fg .executables: app.xa9fg

app.xa9fg: |app.pa9fg

-include package/cfg/app.xa9fg.mak
app.xa9fg: package/cfg/app_pa9fg.oa9fg 
	$(RM) $@
	@$(MSG) lnka9fg $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.A9F.rootDir)/bin/arm-none-eabi-gcc -mfloat-abi=hard -nostartfiles -Wl,-static -Wl,--gc-sections    -o $@ package/cfg/app_pa9fg.oa9fg -Wl,-T,package/cfg/app_pa9fg.xdl   -LC:/ti/bios_6_76_03_01/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/lib/hard -Wl,--start-group -lgcc -lc -lm -Wl,--end-group --specs=nano.specs -Wl,-Map=$(XDCCFGDIR)/$@.map --specs=nosys.specs
	
app.xa9fg: export LD_LIBRARY_PATH=

app.test test,a9fg test: app.xa9fg.test

app.xa9fg.test:: app.xa9fg
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xa9fg.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xa9fg, ) 
endif

clean,a9fg::
	-$(RM) $(wildcard .tmp,app.xa9fg,*)


clean:: clean,a9fg

clean,a9fg::
	-$(RM) app.xa9fg
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_pa9fg.oa9fg,copy : package/cfg/app_pa9fg.oa9fg
app_pa9fg.sa9fg,copy : package/cfg/app_pa9fg.sa9fg

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,xconfig_app
ifeq (,$(MK_NOGENDEPS))
-include package/rel/xconfig_app.tar.dep
endif
package/rel/xconfig_app/xconfig_app/package/package.rel.xml: package/package.bld.xml
package/rel/xconfig_app/xconfig_app/package/package.rel.xml: package/build.cfg
package/rel/xconfig_app/xconfig_app/package/package.rel.xml: package/package.xdc.inc
package/rel/xconfig_app/xconfig_app/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

xconfig_app.tar: package/rel/xconfig_app.xdc.inc package/rel/xconfig_app/xconfig_app/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/xconfig_app.xdc.inc,package/rel/xconfig_app.tar.dep)


release release,xconfig_app: all xconfig_app.tar
clean:: .clean
	-$(RM) xconfig_app.tar
	-$(RM) package/rel/xconfig_app.xdc.inc
	-$(RM) package/rel/xconfig_app.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
